### PR TITLE
Some Changes I made to make it faster

### PR DESCRIPTION
**Pull request by copying**
:)

### CODE REVIEW

**Comment by PringlePot** [comment]
very fast 💯

**Comment by MantyTheSeggsy** [comment]
Thanks

**Comment by copying** [comment]
Thanks
> very fast 💯

**Comment by oTeun** [comment]
No thank you

**Comment by oTeun** [comment]
No thank you

**Comment by PringlePot** [comment]
😢

**Comment by fokshadev** [comment]
:(

**Pull request closed without merging**
